name: The Chicago Way
favicon: null
layout_spectrum: 0.04529090551659465
typography_spectrum: 0.5736974952742457
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5474693987052888
  lightness: 0.7684918933082372
  saturation: 0.8160514300689101
  rhythmicContrast: 0.41332448995672166
purpose: []
